# Generated by Django 5.1.2 on 2025-04-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='motive',
            field=models.CharField(blank=True, choices=[('A', 'Adulto de tercera edad.'), ('B', 'Mujer embarazada.'), ('C', 'Persona en silla de ruedas o muletas.'), ('D', 'Otros.')], max_length=100, null=True),
        ),
    ]
