# Generated by Django 5.1.6 on 2025-04-10 00:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('puntoAcceso', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioPuntoAcceso',
            fields=[
                ('id_puntoAcceso', models.ForeignKey(db_column='id_puntoAcceso', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='puntoAcceso.puntoacceso')),
                ('hora_atencion', models.DateTimeField(blank=True, null=True)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuarioPuntoAcceso',
                'unique_together': {('id_puntoAcceso', 'id_usuario')},
            },
        ),
    ]
