# Generated by Django 5.1.6 on 2025-05-05 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=200, verbose_name='Servicio Solicitado')),
                ('is_priority', models.BooleanField(default=False, verbose_name='Es Prioritario')),
                ('ticket_number', models.CharField(blank=True, max_length=10, unique=True, verbose_name='Número de Ticket')),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('LLAMADO', 'Llamado'), ('ATENDIDO', 'Atendido'), ('CANCELADO', 'Cancelado'), ('NO_ASISTIO', 'No Asistió')], default='PENDIENTE', max_length=20, verbose_name='Estado del Ticket')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Solicitante')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-created_at'],
            },
        ),
    ]
