# Generated by Django 5.1.6 on 2025-05-06 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='modality',
            field=models.CharField(choices=[('VIRTUAL', 'Virtual'), ('PRESENCIAL', 'Presencial')], default='PRESENCIAL', max_length=20, verbose_name='Modalidad del Servicio'),
        ),
    ]
