# Generated by Django 5.1.2 on 2025-04-24 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_actor_motive'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_priority', models.BooleanField(default=False)),
                ('horario_apertura', models.TimeField()),
                ('horario_cierre', models.TimeField()),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.worker')),
            ],
        ),
        migrations.CreateModel(
            name='AccessPointActor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('access_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puntosAcceso.accesspoint')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.actor')),
            ],
        ),
    ]
