# Generated by Django 5.1.2 on 2025-04-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puntosAcceso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesspoint',
            name='horario_apertura',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='accesspoint',
            name='horario_cierre',
            field=models.TimeField(null=True),
        ),
    ]
