# Generated by Django 5.1.6 on 2025-04-10 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PuntoAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_atencion', models.TimeField(blank=True, db_column='horario_atencion', null=True)),
                ('discapacitados', models.BooleanField(db_column='discapacitados', default=False)),
            ],
            options={
                'db_table': 'puntoAcceso',
            },
        ),
    ]
