# Generated by Django 5.1.6 on 2025-03-19 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '__first__'),
        ('ticket', '__first__'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('codigo', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tiene_prioridad', models.BooleanField(default=False)),
                ('id_ticket', models.ForeignKey(db_column='id_ticket', on_delete=django.db.models.deletion.CASCADE, to='ticket.ticket')),
                ('rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.CASCADE, to='rol.rol')),
            ],
        ),
        migrations.DeleteModel(
            name='Atencion',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
