# Generated by Django 5.1.2 on 2025-03-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_rename_rol_usuario_id_rol_usuario_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='123', max_length=200, unique=True),
        ),
    ]
